services:
  backend:
    build:
      dockerfile: etc/docker/Dockerfile.dev
      context: .
    restart: always
    env_file: .env
    volumes:
      - ./src/:/app/
      - ./cdn/static/:/cdn/static/
      - ./cdn/media/:/cdn/media/
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"

  celery:
    build:
      dockerfile: etc/docker/Dockerfile.dev
      context: .
    restart: always
    command: bash -c "celery -A django_project.celery.app worker -B -l INFO -Q celery"
    volumes:
      - ./src/:/app/
      - ./cdn/static/:/cdn/static/
      - ./cdn/media/:/cdn/media/
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
